# config.yml

app:
  date_layout: "2006-01-02"
  # Число одновременных запросов к серверу, по заданию равно 1
  max_requests: 1
  generator_preset:
    # Число генерируемых фактов для теста
    facts: 10
    # Данные из задания
    period_start: "2024-05-01"
    period_end: "2024-05-31"
    period_key: "month"
    mo_id: "227373"
    mo_fact_id: "0"
    is_plan: "0"

logging:
  # Accepted levels: trace, debug, info, warning, error
  level: debug
  disable_timestamp: false
  full_timestamp: true
  # If true, report_caller setting will be based on level being trace
  # If false, report_caller setting will use the config value
  level_based_report: true
  report_caller: true
  disable_level_truncation: true
